---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Job

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
    with:
      markdownlint-flags: --config=.github/configs/markdownlint.yaml
  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
    with:
      commitlint-flags: --config=.github/configs/commitlintrc.yaml
