---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Job

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@e3a95ef75601e0b811d0e3f1b9afc04a175acb22 # v3.6.0
  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@e3a95ef75601e0b811d0e3f1b9afc04a175acb22 # v3.6.0
  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@e3a95ef75601e0b811d0e3f1b9afc04a175acb22 # v3.6.0
